#!/usr/bin/env bash
# bootstrap-turtle.sh — install Hermes Agent v0.12 + pgvector_memory plugin on a turtle.
#
# Usage:
#   bootstrap-turtle.sh <turtle-name> <ssh-target>
#
# Example:
#   bootstrap-turtle.sh raphael mastalink@192.168.40.70
#
# Required env vars (sourced from moses3 .env):
#   SUPABASE_URL, SUPABASE_KEY  — Supabase project credentials
#   NVIDIA_API_KEY              — for NVIDIA NIM (default provider)
#   OPENAI_API_KEY              — fallback / alternate provider
#
# Optional:
#   PROVIDER     — Hermes inference provider (default: "nvidia")
#   MODEL        — model id (default: provider's pick)
#   HERMES_HOME  — path on the remote (default: ~/.hermes)

set -euo pipefail

if [ "$#" -lt 2 ]; then
    echo "usage: $0 <turtle-name> <ssh-target>" >&2
    echo "example: $0 raphael mastalink@192.168.40.70" >&2
    exit 1
fi

TURTLE="$1"
SSH_TARGET="$2"
PROVIDER="${PROVIDER:-nvidia}"
MODEL="${MODEL:-}"
REMOTE_HERMES_HOME="${HERMES_HOME:-\$HOME/.hermes}"

# Required from env
: "${SUPABASE_URL:?SUPABASE_URL not set — source moses3 .env first}"
: "${SUPABASE_KEY:?SUPABASE_KEY not set — source moses3 .env first}"

# Provider-specific creds
case "$PROVIDER" in
    nvidia)        : "${NVIDIA_API_KEY:?NVIDIA_API_KEY not set}" ;;
    openai-codex)  : "${OPENAI_API_KEY:?OPENAI_API_KEY not set}" ;;
    openai)        : "${OPENAI_API_KEY:?OPENAI_API_KEY not set}" ;;
esac

DEPLOY_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_DIR="$(cd "$DEPLOY_DIR/.." && pwd)/pgvector_memory"
SOUL_FILE="$DEPLOY_DIR/souls/${TURTLE}.md"

if [ ! -f "$SOUL_FILE" ]; then
    echo "error: soul file not found: $SOUL_FILE" >&2
    echo "available souls:" >&2
    ls "$DEPLOY_DIR/souls/" 2>/dev/null >&2 || echo "  (none)" >&2
    exit 1
fi

if [ ! -d "$PLUGIN_DIR" ]; then
    echo "error: plugin dir not found: $PLUGIN_DIR" >&2
    exit 1
fi

echo ">> turtle:    $TURTLE"
echo ">> ssh:       $SSH_TARGET"
echo ">> provider:  $PROVIDER"
echo ">> model:     ${MODEL:-(provider default)}"
echo ">> soul:      $SOUL_FILE"
echo ">> plugin:    $PLUGIN_DIR"
echo

# ─────────────────────────────────────────────────────────────────────────────
# Step 1: Install Hermes (idempotent — installer checks for existing install)
# ─────────────────────────────────────────────────────────────────────────────
echo "[1/6] Installing Hermes Agent v0.12 on $SSH_TARGET..."
ssh "$SSH_TARGET" 'bash -lc "
    set -e
    if command -v hermes >/dev/null 2>&1; then
        echo \"  hermes already installed: \$(hermes --version 2>&1 || echo unknown)\"
    else
        echo \"  running install.sh from hermes-agent.nousresearch.com\"
        curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash
    fi
"'

# ─────────────────────────────────────────────────────────────────────────────
# Step 2: Ensure HERMES_HOME exists, write SOUL.md
# ─────────────────────────────────────────────────────────────────────────────
echo "[2/6] Installing SOUL.md..."
scp -q "$SOUL_FILE" "$SSH_TARGET:/tmp/SOUL.md"
ssh "$SSH_TARGET" "
    mkdir -p $REMOTE_HERMES_HOME/plugins
    mv /tmp/SOUL.md $REMOTE_HERMES_HOME/SOUL.md
    echo \"  SOUL.md installed at $REMOTE_HERMES_HOME/SOUL.md\"
"

# ─────────────────────────────────────────────────────────────────────────────
# Step 3: Copy pgvector_memory plugin into HERMES_HOME/plugins/
# ─────────────────────────────────────────────────────────────────────────────
echo "[3/6] Installing pgvector_memory plugin..."
# Make a clean tarball without __pycache__
PLUGIN_TGZ="$(mktemp -t pgvector_memory.XXXXXX.tar.gz)"
trap 'rm -f "$PLUGIN_TGZ"' EXIT
tar --exclude='__pycache__' --exclude='*.pyc' -czf "$PLUGIN_TGZ" -C "$(dirname "$PLUGIN_DIR")" "$(basename "$PLUGIN_DIR")"
scp -q "$PLUGIN_TGZ" "$SSH_TARGET:/tmp/pgvector_memory.tgz"
ssh "$SSH_TARGET" "
    rm -rf $REMOTE_HERMES_HOME/plugins/pgvector_memory
    tar -xzf /tmp/pgvector_memory.tgz -C $REMOTE_HERMES_HOME/plugins
    rm /tmp/pgvector_memory.tgz
    echo \"  plugin installed at $REMOTE_HERMES_HOME/plugins/pgvector_memory\"
"

# ─────────────────────────────────────────────────────────────────────────────
# Step 4: Write Hermes config + .env (env file Hermes auto-loads)
# ─────────────────────────────────────────────────────────────────────────────
echo "[4/6] Writing Hermes config + env..."

# Build config from template
TMP_CFG="$(mktemp -t hermes-config.XXXXXX.yaml)"
trap 'rm -f "$PLUGIN_TGZ" "$TMP_CFG"' EXIT
sed -e "s|\${PROVIDER}|$PROVIDER|g" -e "s|\${MODEL}|$MODEL|g" \
    "$DEPLOY_DIR/cli-config.template.yaml" > "$TMP_CFG"

# Build .env for the turtle (only the keys the plugin + provider need)
TMP_ENV="$(mktemp -t hermes-env.XXXXXX)"
trap 'rm -f "$PLUGIN_TGZ" "$TMP_CFG" "$TMP_ENV"' EXIT
{
    echo "# Generated by bootstrap-turtle.sh — do not edit by hand."
    echo "SUPABASE_URL=$SUPABASE_URL"
    echo "SUPABASE_KEY=$SUPABASE_KEY"
    echo "SUPABASE_AGENT_IDENTITY=$TURTLE"
    case "$PROVIDER" in
        nvidia)        echo "NVIDIA_API_KEY=$NVIDIA_API_KEY" ;;
        openai-codex)  echo "OPENAI_API_KEY=$OPENAI_API_KEY" ;;
        openai)        echo "OPENAI_API_KEY=$OPENAI_API_KEY" ;;
    esac
} > "$TMP_ENV"

scp -q "$TMP_CFG" "$SSH_TARGET:/tmp/hermes-config.yaml"
scp -q "$TMP_ENV" "$SSH_TARGET:/tmp/hermes.env"
ssh "$SSH_TARGET" "
    mv /tmp/hermes-config.yaml $REMOTE_HERMES_HOME/cli-config.yaml
    mv /tmp/hermes.env $REMOTE_HERMES_HOME/.env
    chmod 600 $REMOTE_HERMES_HOME/.env
    echo \"  cli-config.yaml + .env installed in $REMOTE_HERMES_HOME\"
"

# ─────────────────────────────────────────────────────────────────────────────
# Step 5: hermes doctor — verify install
# ─────────────────────────────────────────────────────────────────────────────
echo "[5/6] Running hermes doctor on $SSH_TARGET..."
ssh "$SSH_TARGET" 'bash -lc "hermes doctor 2>&1 | head -50"' || echo "  (doctor returned non-zero; review output)"

# ─────────────────────────────────────────────────────────────────────────────
# Step 6: One-shot test — say hi as the turtle
# ─────────────────────────────────────────────────────────────────────────────
echo "[6/6] Quick smoke chat..."
ssh "$SSH_TARGET" 'bash -lc "hermes -z \"Brother, identify yourself in one sentence.\" 2>&1 | tail -10"' || echo "  (one-shot returned non-zero; review output)"

echo
echo ">> done. $TURTLE is up. SOUL.md and pgvector_memory plugin installed."
echo ">> To open an interactive session:    ssh $SSH_TARGET 'hermes'"
echo ">> To verify memory write/read:       ssh $SSH_TARGET 'hermes -z \"Run brain_stats.\"'"
